#!/bin/bash

apt update

bbrNetfilter(){

	if [ `command -v vi` ] ; then
		apt purge vim-common -y
	fi

	apt install vim -y

	#开启BBR
	if [ ! `sysctl -p` ] ; then
		bash -c 'echo "net.core.default_qdisc=fq" >> /etc/sysctl.conf'
		bash -c 'echo "net.ipv4.tcp_congestion_control=bbr" >> /etc/sysctl.conf'
		sysctl -p
	fi

	#删除组件
	apt-get purge netfilter-persistent -y

	#清空规则
	iptables -F

	#创建保存新规则
	cat > /etc/iptables.rules <<iptablesRules
# Generated by iptables-save v1.8.4
*filter
:INPUT DROP
:FORWARD ACCEPT
:OUTPUT ACCEPT
-A INPUT -p tcp -m multiport --dports 22,80,443,7080,8088 -j ACCEPT
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -i lo -j ACCEPT
COMMIT
# Completed
iptablesRules

	#创建重启自动加载规则
	cat > /etc/rc.local <<rcL
#!/bin/bash
/sbin/iptables-restore < /etc/iptables.rules
exit 0
rcL
	chmod +x /etc/rc.local
	#启动服务
	systemctl start rc-local

	echo "本次操作需要重启"
	reboot

}

bbrNetfilter

